spring:
  application:
    name: 'api-gateway'
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

server:
  port: ${GATEWAY_SERVER_PORT:8765}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://service-discovery:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${server.port}