spring:
  openfeign:
    okhttp:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connection-timeout: 10000

springdoc:
  openapi:
    title: 'BFF Helpdesk API'
    description: 'Component responsible for aggregating and exposing the Helpdesk APIs'
    version: '1.0.0'

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: 'fteCGmFQxqIIPYzz5X2AD3Ft64ZSgQ0PugoYWkoF5+uMrC+bDfSIl6WMk/qL+dunFLI5foEtDcIopX/atgLXmVxZkEs9GXiyaEPOwRD5dbk='

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${server.port}