spring:
  application:
    name: 'auth-service-api'

jwt:
  secret: 'fteCGmFQxqIIPYzz5X2AD3Ft64ZSgQ0PugoYWkoF5+uMrC+bDfSIl6WMk/qL+dunFLI5foEtDcIopX/atgLXmVxZkEs9GXiyaEPOwRD5dbk='
  expiration: 7200000 # 2 hours

server:
  port: 8081