spring:
  application:
    name: 'auth-service-api'
  data:
    mongodb:
      uri: 'mongodb+srv://help-desk-user:h3lp-D3sk-u53r@clusterhelpdesk.byesqfs.mongodb.net/helpdeskdb?retryWrites=true&w=majority&appName=ClusterHelpDesk'

jwt:
  secret: 'fteCGmFQxqIIPYzz5X2AD3Ft64ZSgQ0PugoYWkoF5+uMrC+bDfSIl6WMk/qL+dunFLI5foEtDcIopX/atgLXmVxZkEs9GXiyaEPOwRD5dbk='
  expiration: 7200000 # 2 hours

jwt:
  secret: 'fteCGmFQxqIIPYzz5X2AD3Ft64ZSgQ0PugoYWkoF5+uMrC+bDfSIl6WMk/qL+dunFLI5foEtDcIopX/atgLXmVxZkEs9GXiyaEPOwRD5dbk='
  expiration: 7200000 # 2 hours

server:
  port: 8081